[build]
  command = "prisma migrate deploy && prisma generate && next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-prisma"

[build.environment]
  NODE_ENV = "production"
  DATABASE_URL = "your_database_url"
