[build]
  command = "next build"
  publish = ".next"
  functions = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_NODE_ENV = "production"
