[build]
  command = "prisma migrate deploy && prisma generate && next build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "postgresql://Zuma-base-Url_owner:j51HxqgziFAw@ep-cold-scene-a168x3t6.ap-southeast-1.aws.neon.tech/Zuma-base-Url?sslmode=require"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"
